sequenceDiagram
    participant client as User Client
    participant browser as Web Browser
    participant server

    client->>browser: Type some text in input form
    client->>browser: Press save button
    browser->>server: Send Http Post /new_note resource
    Note right of browser: Body payload goes with input text value

    activate server
    server-->>browser: Response with status code 302
    Note left of server: Server sends a URL redirect to /note page
    deactivate server

    Note right of browser: The browser does a new HTTP GET request to the address defined in the header's Location
    Note right of browser: The browser reloads the Notes page. The reload causes three more HTTP requests

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "HTML is easy", "date": "2023-1-1" }, ... ]
    deactivate server

    Note right of browser: The browser executes the callback function that renders the notes again!!
